from pygame import K_RIGHT, K_LEFT

# Screen Attributes
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
SCREEN_BACKGROUND_COLOR = "black"
FRAME_RATE = 60

# Brick Attributes
BRICK_WIDTH = SCREEN_WIDTH // 15
BRICK_HEIGHT = SCREEN_HEIGHT // 30
BRICK_PADDING = SCREEN_WIDTH // 250

# Paddle Attributes
PADDLE_WIDTH = SCREEN_WIDTH // 10
PADDLE_HEIGHT = SCREEN_HEIGHT // 50
PADDLE_SPEED = PADDLE_WIDTH // 10
PADDLE_MOVE_RIGHT = K_RIGHT
PADDLE_MOVE_LEFT = K_LEFT

# Ball Attributes
BALL_RADIUS = PADDLE_WIDTH // 10
BALL_SPEED = BALL_RADIUS // 1.3
BALL_COLLISION_BUFFER = BALL_RADIUS * BALL_SPEED

# PowerUp Attributes
POWERUP_WIDTH = BRICK_WIDTH // 5
POWERUP_HEIGHT = BRICK_HEIGHT // 2
POWERUP_SPEED = BALL_SPEED // 3
